# Welcome to Jekyll!
#
# この設定ファイルは、ブログ全体に影響を与える設定のためのもので、一度設定すればその後はほとんど編集することはありません。このファイルを頻繁に編集するようであれば、Jekyllのデータファイル機能を使って、頻繁に更新する必要のあるデータを保存することを検討してください。
#
# 技術的な理由により、'bundle exec jekyll serve'を使用した場合、このファイルは自動的にリロードされません。このファイルを変更した場合は、サーバープロセスを再起動してください。
#
# YAMLの構文についてヘルプが必要な場合、ここに簡単なリファレンスがあります：
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# サイトの設定
# これらは新しいサイトをパーソナライズするために使われます。HTMLファイルを見ると, {{ site.title }}, {{ site.email }} などでアクセスできることがわかります.
# お望みのカスタム変数を作成することができ, テンプレートから {{ site.myvariable }}経由でアクセスすることができます.

title: 白書大木
email: 041.whitepaper@gmail.com
description: >- # これは "baseurl: "までの改行を無視することを意味する。
  ブログ
author: Oki Whitepaper
twitter_username: wp_041
github_username: wp041
google_analytics: G-B8H50J7XT4
excerpt_separator: "<!--抜粋ここまで-->"

future: true # これをするとなんかgithubpagesで困らない
kramdown:
  input: GFM
  autolink: true #これいらないかも
  hard_wrap: true
include:
  - _pages

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /article/:title
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  # 全て
  - scope:
      path: ""
    values:
      layout: "default"

# Build settings
# theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
